### PR TITLE
Merge feature-a into branch main branch

### PR DESCRIPTION
**Pull request by Timbar09**
- Added .gitignore
- Added linters
- added index.html, style.css
- Added README.md

### CODE REVIEW

**Review by binhussen — CHANGES_REQUESTED** [review]
Hi @Timbar09 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Used GitHub flow ✔️

## Required Changes ♻️
- [REQUIRED] Please configure the linter based on these [steps](https://github.com/microverseinc/linters-config/tree/master/html-css)
- [RQUIRED] Kindly, add a description for your Pull Request telling what changes are inside.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Timbar09** [comment]
#Changes made

- Added linters to the repo
- Added index.html, style.css files
- Added test.md
- Added .ignore file which ihnores node_modules and test.md

**Review by levy002 — CHANGES_REQUESTED** [review]
## Hello @Timbar09   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!



## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] As requested by the previous reviewer, kindly make sure to edit your PR description.

  _**Example of how you can edit your PR description**_
   chrome-capture-2022-10-30 (1)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Felix45 — APPROVED** [review]
# Approved :green_circle: 
Hi @Timbar09 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights :heavy_check_mark: 
- [ ] Implemented all changes requested by previous reviewers :white_check_mark: 
- [ ] All linter checks are passing :white_check_mark: 

Congratulations-Memes-FEATURED

## Optional suggestions
- [ Optional ] In future projects please consider giving your pull requests descriptive titles, the current title is not descriptive. A better title for this pull request could have been a title like. This is highly recommended for future projects.
## Milestone: Add Hello Microverse home page
- [ Optional] In future projects please consider giving the branches in your project descriptive names, the currrent branch name is not descriptive. An example of a descriptive name for this branch could have been a name such as `add-hello-microverse-page`, `created_hello_microverse_page` or `added_hello_microverse_page` This is highly recommended for future projects.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
